service: !u FP.Service.ConfigDB
version: 1
classes:
  - !u ACS.Class.EdgeCluster
objects:
  !u ACS.Class.Role:
    - !u ACS.Role.EdgeFlux
  !u ACS.Class.ServiceAccount:
    - !u ACS.Account.EDO
  !u E.Class.Template:
    - !u ACS.EdgeTemplate.CellGateway
configs:
  !u FP.App.Info:
    !u ACS.Class.EdgeCluster: { name: "Edge cluster account" }
    !u ACS.Role.EdgeFlux: { name: "Edge flux" }
    !u ACS.Account.EDO: { name: "Edge Deployment Operator" }
    !u ACS.EdgeTemplate.CellGateway: { name: "Cell Gateway" }
  !u E.App.Template
    !u ACS.EdgeTemplate.CellGateway:
      {
          "flux": {
              "name": "Edge flux: %n",
              "class": "97756c9a-38e6-4238-b78c-3df6f227a6c9",
              "groups": [
                  "34ee0e7f-8c9c-4f6d-aad7-4ed700bc77da"
              ],
              "username": "op1flux/%n"
          },
          "name": "cell-gateway",
          "cluster": {
              "namespace": "fplus-edge"
          },
          "repository": {
              "group": "cluster",
              "links": {
                  "8a3c0860-9e41-48b8-b02f-780a0e582be6": {
                      "branch": "main",
                      "interval": "3h0m0s"
                  }
              },
              "branch": "main",
              "interval": "5m0s"
          }
      }
